language: csharp
solution: testWebAppReact.sln
sudo: required
mono: none
dotnet: 3.0

before_install:
  - sudo docker run --privileged furman9596/binfmf-with-dotnet:latest
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit furman9596/buildkit-with-dotnet:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  
install: true

script:
 - dotnet test

deploy:
 provider: script
 script: bash ./scripts/deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
 skip_cleanup: true
 on:
  tags: true




after_success:
 - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh success $WEBHOOK_URL
after_failure:
 - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh failure $WEBHOOK_URL

notifications:
 email: false